services:
  web:
    image: locasso-web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "9090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=locasso;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=locasso
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
