// This file is a placeholder for the actual migration that will be created
// by running the EF Core migration commands:
//
// dotnet ef migrations add InitialMigration --project src/Web/Web.csproj
// dotnet ef database update --project src/Web/Web.csproj
//
// The actual migration will be generated by these commands. 